spring.application.name=aaaconfigservertrainingtracker
server.servlet.context-path=/aaaconfigservertrainingtracker

server.port=8071

spring.profiles.active=git
  
spring.cloud.config.server.git.uri=https://github.com/Yashpalgawali/training-tracker-config.git
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.timeout=5

# This encrypt key is used to encrypt the username and password of the email 
# Without this Key we can't receive the Decrypted Email and the Password from the config files
encrypt.key=1a57a671f809d9137134caecc3a407fcc99094f25e7d4b0d68bec67259b460c5

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.org.springframework.boot.actuate=DEBUG
logging.level.org.springframework.cloud.config=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest